// 此文件为自动生成而成。请不要手动修改。
/**
 *
 *  API 请求名枚举列表
 */
export const enum ReqNames {
  Sigin = "Sigin",
  Logout = "Logout",
  GetUserInfo = "GetUserInfo",
  GetBedList = "GetBedList",
  PostBed = "PostBed",
  PutBed = "PutBed",
  DeleteBed = "DeleteBed",
  GetCampusList = "GetCampusList",
  PostCampus = "PostCampus",
  PutCampus = "PutCampus",
  DeleteCampus = "DeleteCampus",
  GetCollegeList = "GetCollegeList",
  PostCollege = "PostCollege",
  Put = "Put",
  DeleteCollege = "DeleteCollege",
  GetStudentFee = "GetStudentFee",
  GetFee = "GetFee",
  PutFee = "PutFee",
  DeleteFee = "DeleteFee",
  GetFeeList = "GetFeeList",
  PostFee = "PostFee",
  GetFile = "GetFile",
  GetGreenChannelList = "GetGreenChannelList",
  PostGreenChannel = "PostGreenChannel",
  GetGreenChannel = "GetGreenChannel",
  PutGreenChannel = "PutGreenChannel",
  DeleteGreenChannel = "DeleteGreenChannel",
  GetInfoCategoryList = "GetInfoCategoryList",
  PutInfoCategory = "PutInfoCategory",
  PostInfoCategory = "PostInfoCategory",
  GetInfoCategoryItem = "GetInfoCategoryItem",
  DeleteInfoCategory = "DeleteInfoCategory",
  GetLeave = "GetLeave",
  PostLeave = "PostLeave",
  GetLeaveList = "GetLeaveList",
  PutLeave = "PutLeave",
  DeleteLeave = "DeleteLeave",
  GetMajorList = "GetMajorList",
  PostMajor = "PostMajor",
  PutMajor = "PutMajor",
  DeleteMajor = "DeleteMajor",
  GetNewsList = "GetNewsList",
  PostNews = "PostNews",
  GetNews = "GetNews",
  PutNews = "PutNews",
  DeleteNews = "DeleteNews",
  GetPaymentList = "GetPaymentList",
  PostPayment = "PostPayment",
  PutPayment = "PutPayment",
  DeletePayment = "DeletePayment",
  GetStudentList = "GetStudentList",
  PostStudent = "PostStudent",
  GetStudent = "GetStudent",
  PutStudent = "PutStudent",
  DeleteStudent = "DeleteStudent",
  GetUserList = "GetUserList",
  PostUser = "PostUser",
  GetUser = "GetUser",
  PutUser = "PutUser",
  DeleteUser = "DeleteUser"
}
