/**
 * yxAPI
 *
 *
 * version v1
 *
 *
 * NOTE: This class is auto generated by the code generator.
 * Do not edit the class manually.
 */
import * as m from "./models";
import { encodeQuery } from "@/utils";
import { Log } from "@/logbox";
import { apiSendAsync, ApiRequestOptions } from "@/utils/apiRequest";

const defaultPageSize = 20;

const protocol = "https";
export const apiHost = process.env.VUE_APP_API_HOST;
const basePath = "";
export const baseUrl = `${protocol}://${apiHost}`;
export const wssBaseUrl = `wss://${apiHost}${basePath}/ws`;

/*
    export interface m.DataResponse&lt;m.TokenObj&gt; extends m.CommonResp{
      data?: m.TokenObj;
    }
*/

/**
 * 登陆获取token
 * @param signinForm m.SigninForm
 */
export function Sigin(options: {
  signinForm: m.SigninForm;
}): Promise<m.DataResponse<m.TokenObj>> {
  const opts: ApiRequestOptions = {
    url: `/api/Auth`,
    method: "post",
    reqName: "Sigin"
  };

  opts.data = options.signinForm;
  return apiSendAsync<m.DataResponse<m.TokenObj>>(opts);
}
/*
    export interface m.DataResponse&lt;m.Student&gt; extends m.CommonResp{
      data?: m.Student;
    }
*/

/**
 *
 * @param student m.Student
 */
export function Post(options: {
  student?: m.Student;
}): Promise<m.DataResponse<m.Student>> {
  const opts: ApiRequestOptions = {
    url: `/api/Student`,
    method: "post",
    reqName: "Post"
  };

  opts.data = options.student;
  return apiSendAsync<m.DataResponse<m.Student>>(opts);
}
/*
    export interface m.DataResponse&lt;undefined&gt; extends m.CommonResp{
      data?: ;
    }
*/

/**
 *
 */
export function Get(): Promise<m.DataResponse<undefined>> {
  const opts: ApiRequestOptions = {
    url: `/api/Values`,
    method: "get",
    reqName: "Get"
  };

  return apiSendAsync<m.DataResponse<undefined>>(opts);
}
/*
    export interface m.DataResponse&lt;undefined&gt; extends m.CommonResp{
      data?: ;
    }
*/

/**
 *
 * @param value string
 */
export function Post(options: {
  value?: string;
}): Promise<m.DataResponse<undefined>> {
  const opts: ApiRequestOptions = {
    url: `/api/Values`,
    method: "post",
    reqName: "Post"
  };

  opts.data = options.value;
  return apiSendAsync<m.DataResponse<undefined>>(opts);
}
/*
    export interface m.DataResponse&lt;undefined&gt; extends m.CommonResp{
      data?: ;
    }
*/

/**
 *
 * @param id number integer
 * @param value string
 */
export function Put(options: {
  id: number;
  value?: string;
}): Promise<m.DataResponse<undefined>> {
  const opts: ApiRequestOptions = {
    url: `/api/Values/${options.id}`,
    method: "put",
    reqName: "Put"
  };

  opts.data = options.value;
  return apiSendAsync<m.DataResponse<undefined>>(opts);
}
/*
    export interface m.DataResponse&lt;undefined&gt; extends m.CommonResp{
      data?: ;
    }
*/

/**
 *
 * @param id number integer
 */
export function Delete(options: {
  id: number;
}): Promise<m.DataResponse<undefined>> {
  const opts: ApiRequestOptions = {
    url: `/api/Values/${options.id}`,
    method: "delete",
    reqName: "Delete"
  };

  return apiSendAsync<m.DataResponse<undefined>>(opts);
}
